server:
  port: 9527


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
  instance:
    hostname: cloud-gateway-service

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 4000
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000

#logging:
#  level:
#    # feign日志以什么级别监控哪个接口
#    com.springcloud.service.Service: debug

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            - After=2020-07-14T08:37:42.774+08:00[Asia/Shanghai]
#            - Cookie=xm,pmf
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            Path=/payment/timeOut #断言,路径相匹配的进行路由
